### ISSUE TITLE
没能run成功生成app.json

### ISSUE THREAD

**Issue by c747903646** [kennylbj/patrick-wechat#7]
求教如何解决！执行`yarn run dev:weapp`之后会有如下提示：

yarn run v1.22.5
$ npm run build:weapp -- --watch

> patrick-wechat@3.0.0 build:weapp D:\Document\Works\WeChat\example\patrick-wechat-master
> taro build --type weapp "--watch"

👽 Taro v3.2.1

(node:4040) UnhandledPromiseRejectionWarning: Error: Cannot find module '@tarojs/plugin-platform-weapp' from 'D:\Document\Works\WeChat\example\patrick-wechat-master'
    at Function.resolveSync [as sync] (C:\Users\Aquamarine\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\service\node_modules\resolve\lib\sync.js:81:15)
    at C:\Users\Aquamarine\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\utils\index.js:46:31
    at Array.map (<anonymous>)
    at Object.resolvePresetsOrPlugins (C:\Users\Aquamarine\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\utils\index.js:45:30)
    at Kernel.resolvePlugins (C:\Users\Aquamarine\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:90:36)
    at Kernel.initPresetsAndPlugins (C:\Users\Aquamarine\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:81:14)
    at Kernel.<anonymous> (C:\Users\Aquamarine\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:40:18)
    at Generator.next (<anonymous>)
    at C:\Users\Aquamarine\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:8:71
    at new Promise (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:4040) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 3.52s.

**Comment by kennylbj** [comment]
首先看看本地是否安装了taro，然后核对一下版本，最好和项目的taro版本一致(3.0.x)。

```
taro -v
```

如果不一致建议回退到3.0版本，因为本项目还没升级到最新taro cli

**Comment by c747903646** [comment]
已将taro回退到3.0.7，开始生成project.config.json了，但是出现了“ Cannot read property 'isSupportRecursive' of undefined”的错误提示orz，请问是否知道这个的解决方案？

话说会不会和node.js的版本有关系？我现在的相关框架版本如下：
👽 Taro v3.0.7


  Taro CLI 3.0.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD

报错具体log如下：
Duplicate of 

$ npm run build:weapp -- --watch

> patrick-wechat@3.0.0 build:weapp D:\Document\Works\WeChat\example\patrick-wechat-master
> taro build --type weapp "--watch"

👽 Taro v3.0.7

Tips: 预览模式生成的文件较大，设置 NODE_ENV 为 production 可以开启压缩。
Example:
$ set NODE_ENV=production && taro build --type weapp --watch

生成  工具配置  D:\Document\Works\WeChat\example\patrick-wechat-master\dist/project.config.json
(node:2312) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isSupportRecursive' of undefined
    at new TaroMiniPlugin (D:\Document\Works\WeChat\example\patrick-wechat-master\node_modules\@tarojs\mini-runner\src\plugins\MiniPlugin.ts:134:18)
    at D:\Document\Works\WeChat\example\patrick-wechat-master\node_modules\webpack-chain\src\Plugin.js:13:18
    at Object.toConfig (D:\Document\Works\WeChat\example\patrick-wechat-master\node_modules\webpack-chain\src\Plugin.js:47:22)
    at D:\Document\Works\WeChat\example\patrick-wechat-master\node_modules\webpack-chain\src\Config.js:125:61
    at Array.map (<anonymous>)
    at module.exports.toConfig (D:\Document\Works\WeChat\example\patrick-wechat-master\node_modules\webpack-chain\src\Config.js:125:40)
    at module.exports.toString (D:\Document\Works\WeChat\example\patrick-wechat-master\node_modules\webpack-chain\src\Config.js:137:41)
    at Kernel.<anonymous> (C:\Users\Aquamarine\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:185:54)
    at Generator.next (<anonymous>)
    at C:\Users\Aquamarine\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Aquamarine\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:4:12)
    at Kernel.applyPlugins (C:\Users\Aquamarine\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:171:16)
    at C:\Users\Aquamarine\AppData\Roaming\npm\node_modules\@tarojs\cli\src\presets\commands\build.ts:69:25
    at Generator.next (<anonymous>)
    at C:\Users\Aquamarine\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\presets\commands\build.js:8:71
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2312) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 11.02s.

**Comment by lkorcm** [comment]
发生了同样的问题 但在Taro 版本更新至V3.1.1后解决

**Comment by c747903646** [comment]
> 发生了同样的问题 但在Taro 版本更新至V3.1.1后解决

将taro版本安装成3.1.1成功解决，感谢建议。
